# Generated by Django 5.0.4 on 2024-05-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage', models.FloatField(choices=[(24.0, '24 tony'), (7.5, '7,5 tony'), (3.5, '3,5 tony')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HourReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('is_inbound', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('date', 'hour', 'is_inbound')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('reservation_type', models.CharField(choices=[('load', 'Load'), ('unload', 'Unload')], default='load', max_length=100)),
                ('vehicle_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration_slot.vehicletype')),
            ],
            options={
                'unique_together': {('date', 'time_slot', 'reservation_type')},
            },
        ),
    ]
