# Generated by Django 5.0.4 on 2024-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_slot', '0003_service_reservation_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Sorting', 'Sorting'), ('Delivery', 'Delivery')], max_length=100),
        ),
    ]
