# Generated by Django 5.0.4 on 2024-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_slot', '0004_remove_service_name_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Warehouse_1', 'Warehouse_1'), ('Warehouse_2', 'Warehouse_2')], max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
