# Generated by Django 5.0.4 on 2024-05-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_slot', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='registration_slot.location'),
        ),
    ]
